name: Gradle build

on:
  push:
    branches: [ 1.18.2-universal, 1.18.2-server-only ]
  pull_request:
    branches: [ 1.18.2-universal, 1.18.2-server-only ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PUBLISH_SUFFIX: snapshots
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildOrPublish

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/